#!/bin/sh
### BEGIN INIT INFO
# Provides:          lora2mqtt
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: LoRa to MQTT bridge driver
### END INIT INFO
#/etc/init.d/lora2mqtt
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec forever start --sourceDir=SERVER_DIR server.js  #scriptarguments
;;
stop)
exec forever stop --sourceDir=SERVER_DIR server.js
;;
*)
echo "Usage: /etc/init.d/myService {start|stop}"
exit 1
;;
esac
exit 0